---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rp
spec:
  selector:
    matchLabels:
      app: rp
  serviceName: rp
  replicas: 1
  template:
    metadata:
      labels:
        app: rp
    spec:
      containers:
      - name: abci
        image: ndidplatform/abci:latest
        imagePullPolicy: Never
        args: ["tcp://0.0.0.0:46000"]
        ports:
        - containerPort: 46000
      - name: tm
        image: ndidplatform/tendermint:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 45000
        - containerPort: 47000
        env:
        - name: SEED_HOSTNAME
          value: "genesis-service"
        - name: ABCI_PORT
          value: "46000"
        - name: TM_RPC_PORT
          value: "45000"
        - name: TM_P2P_PORT
          value: "47000"
        args: ["secondary", "--proxy_app=tcp://localhost:46000", "--rpc.laddr=tcp://0.0.0.0:45000" , "--p2p.laddr=tcp://0.0.0.0:47000", "--p2p.seeds=genesis-service:47000" ]
      - name: api
        image: ndidplatform/api:latest
        ports:
        - containerPort: 5555
        - containerPort: 8080
        env:
        - name: ROLE
          value: "rp"
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NDID_IP
          value: "genesis-service"
        - name: TENDERMINT_IP
          value: "localhost"
        - name: TENDERMINT_PORT
          value: "45000"
        - name: MQ_CONTACT_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MQ_BINDING_PORT
          value: "5555"
        - name: SERVER_PORT
          value: "8080"
      # - name: example
      #   image: ndidplatform/examples:latest
      #   ports:
      #   - containerPort: 5000
      #   - containerPort: 8000
      #   env:
      #   - name: SERVER_PORT
      #     value: "8000"
      #   - name: API_SERVER_ADDRESS
      #     value: "http://localhost:8080"
      #   - name: NDID_API_CALLBACK_IP
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: status.podIP
      #   - name: NDID_API_CALLBACK_PORT
      #     value: "5000"
      #   args: ["rp"]

