apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: node-discovery-server
  name: node-discovery-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: node-discovery-server
    spec:
      containers:
      - image: watcharaphat/node-discovery-server
        name: node-discovery-server
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
